version: "3.8"

services:
    stock_price_app:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: stock-price-aggregator
        container_name: stock-price-aggregator
        restart: unless-stopped
        ports:
            - 9000:9000
        volumes:
            - .:/var/www
        networks:
            - stock_price_aggregator
        depends_on:
            - stock_price_db

    stock_price_db:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/dbdata:/docker-entrypoint-initdb.d
        networks:
            - stock_price_aggregator

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - stock_price_app
        networks:
            - stock_price_aggregator

networks:
    stock_price_aggregator:
